/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IDODOInterface extends ethers.utils.Interface {
  functions: {
    "_BASE_RESERVE_()": FunctionFragment;
    "_BASE_TOKEN_()": FunctionFragment;
    "_QUOTE_RESERVE_()": FunctionFragment;
    "_QUOTE_TOKEN_()": FunctionFragment;
    "flashLoan(uint256,uint256,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_BASE_RESERVE_",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_BASE_TOKEN_",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_QUOTE_RESERVE_",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_QUOTE_TOKEN_",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoan",
    values: [BigNumberish, BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "_BASE_RESERVE_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_BASE_TOKEN_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_QUOTE_RESERVE_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_QUOTE_TOKEN_",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flashLoan", data: BytesLike): Result;

  events: {};
}

export class IDODO extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IDODOInterface;

  functions: {
    _BASE_RESERVE_(overrides?: CallOverrides): Promise<[BigNumber]>;

    _BASE_TOKEN_(overrides?: CallOverrides): Promise<[string]>;

    _QUOTE_RESERVE_(overrides?: CallOverrides): Promise<[BigNumber]>;

    _QUOTE_TOKEN_(overrides?: CallOverrides): Promise<[string]>;

    flashLoan(
      baseAmount: BigNumberish,
      quoteAmount: BigNumberish,
      assetTo: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _BASE_RESERVE_(overrides?: CallOverrides): Promise<BigNumber>;

  _BASE_TOKEN_(overrides?: CallOverrides): Promise<string>;

  _QUOTE_RESERVE_(overrides?: CallOverrides): Promise<BigNumber>;

  _QUOTE_TOKEN_(overrides?: CallOverrides): Promise<string>;

  flashLoan(
    baseAmount: BigNumberish,
    quoteAmount: BigNumberish,
    assetTo: string,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _BASE_RESERVE_(overrides?: CallOverrides): Promise<BigNumber>;

    _BASE_TOKEN_(overrides?: CallOverrides): Promise<string>;

    _QUOTE_RESERVE_(overrides?: CallOverrides): Promise<BigNumber>;

    _QUOTE_TOKEN_(overrides?: CallOverrides): Promise<string>;

    flashLoan(
      baseAmount: BigNumberish,
      quoteAmount: BigNumberish,
      assetTo: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    _BASE_RESERVE_(overrides?: CallOverrides): Promise<BigNumber>;

    _BASE_TOKEN_(overrides?: CallOverrides): Promise<BigNumber>;

    _QUOTE_RESERVE_(overrides?: CallOverrides): Promise<BigNumber>;

    _QUOTE_TOKEN_(overrides?: CallOverrides): Promise<BigNumber>;

    flashLoan(
      baseAmount: BigNumberish,
      quoteAmount: BigNumberish,
      assetTo: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _BASE_RESERVE_(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _BASE_TOKEN_(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _QUOTE_RESERVE_(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _QUOTE_TOKEN_(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    flashLoan(
      baseAmount: BigNumberish,
      quoteAmount: BigNumberish,
      assetTo: string,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
