/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IDODOV2Interface extends ethers.utils.Interface {
  functions: {
    "querySellBase(address,uint256)": FunctionFragment;
    "querySellQuote(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "querySellBase",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "querySellQuote",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "querySellBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "querySellQuote",
    data: BytesLike
  ): Result;

  events: {};
}

export class IDODOV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IDODOV2Interface;

  functions: {
    querySellBase(
      trader: string,
      payBaseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        receiveQuoteAmount: BigNumber;
        mtFee: BigNumber;
      }
    >;

    querySellQuote(
      trader: string,
      payQuoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        receiveBaseAmount: BigNumber;
        mtFee: BigNumber;
      }
    >;
  };

  querySellBase(
    trader: string,
    payBaseAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { receiveQuoteAmount: BigNumber; mtFee: BigNumber }
  >;

  querySellQuote(
    trader: string,
    payQuoteAmount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { receiveBaseAmount: BigNumber; mtFee: BigNumber }
  >;

  callStatic: {
    querySellBase(
      trader: string,
      payBaseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        receiveQuoteAmount: BigNumber;
        mtFee: BigNumber;
      }
    >;

    querySellQuote(
      trader: string,
      payQuoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        receiveBaseAmount: BigNumber;
        mtFee: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    querySellBase(
      trader: string,
      payBaseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    querySellQuote(
      trader: string,
      payQuoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    querySellBase(
      trader: string,
      payBaseAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    querySellQuote(
      trader: string,
      payQuoteAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
