/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IRouterInterface extends ethers.utils.Interface {
  functions: {
    "getFee(address,address)": FunctionFragment;
    "getRouterAddress(uint8)": FunctionFragment;
    "updateFee(address,address,uint24)": FunctionFragment;
    "updateRouterAddress(uint8,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getFee",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRouterAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFee",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRouterAddress",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRouterAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRouterAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRouter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRouterInterface;

  functions: {
    getFee(
      base: string,
      quote: string,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getRouterAddress(
      routerIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    updateFee(
      base: string,
      quote: string,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateRouterAddress(
      routerIdx: BigNumberish,
      router: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getFee(
    base: string,
    quote: string,
    overrides?: CallOverrides
  ): Promise<number>;

  getRouterAddress(
    routerIdx: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  updateFee(
    base: string,
    quote: string,
    fee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateRouterAddress(
    routerIdx: BigNumberish,
    router: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getFee(
      base: string,
      quote: string,
      overrides?: CallOverrides
    ): Promise<number>;

    getRouterAddress(
      routerIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    updateFee(
      base: string,
      quote: string,
      fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRouterAddress(
      routerIdx: BigNumberish,
      router: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getFee(
      base: string,
      quote: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRouterAddress(
      routerIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateFee(
      base: string,
      quote: string,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateRouterAddress(
      routerIdx: BigNumberish,
      router: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFee(
      base: string,
      quote: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRouterAddress(
      routerIdx: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateFee(
      base: string,
      quote: string,
      fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateRouterAddress(
      routerIdx: BigNumberish,
      router: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
